### ISSUE TITLE
This happened today

### ISSUE THREAD

**Issue by AleksanderGrzybowski** [AleksanderGrzybowski/SmsAlerts#4]
```

9 04:52:10.627  INFO 1 --- [pool-2-thread-1] p.k.s.ksparser.KsParserServiceImpl       : Parsing 72736 bytes...
386 2017-04-29 04:52:10.630  INFO 1 --- [pool-2-thread-1] p.k.s.ksparser.KsParserServiceImpl       : Parsing finished, 20 entries
387 2017-04-29 04:52:10.630  INFO 1 --- [pool-2-thread-1] p.k.s.k.KsDownloaderServiceImpl          : Received 20 entries.
388 2017-04-29 04:52:10.632  INFO 1 --- [pool-2-thread-1] p.k.s.kspoller.KsPollerServiceImpl       : New entry with date29-04-2017 06:40 found, saving.
389 2017-04-29 04:52:10.641  INFO 1 --- [pool-2-thread-1] p.k.s.kspoller.KsPollerServiceImpl       : Entry 29-04-2017 06:40 contains pattern 'Wis�~Ba', sending message.
390 2017-04-29 04:52:10.649 ERROR 1 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.                        
391 
392 pl.kelog.smsalerts.validation.ValidationException: null
393     at pl.kelog.smsalerts.validation.ValidationExceptionBuilder.build(ValidationExceptionBuilder.java:29) ~[classes!/:na]
394     at pl.kelog.smsalerts.validation.ValidationExceptionBuilder.throwIfErrors(ValidationExceptionBuilder.java:24) ~[classes!/:na]
395     at pl.kelog.smsalerts.sms.MessageServiceImpl.sendAndStore(MessageServiceImpl.java:42) ~[classes!/:na]
396     at pl.kelog.smsalerts.kspoller.KsPollerServiceImpl.pollAndSend(KsPollerServiceImpl.java:61) ~[classes!/:na]
397     at pl.kelog.smsalerts.kspoller.KsPollerScheduledTask.reportCurrentTime(KsPollerScheduledTask.java:27) ~[classes!/:na]
398     at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[na:na]
399     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
400     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
401     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
402     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.     7.RELEASE]
403     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
404     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
405     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
406     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
407     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
408     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
409     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
410 
411 2017-04-29 05:07:10.129  INFO 1 --- [pool-2-thread-1] p.k.s.kspoller.KsPollerScheduledTask     : Starting poll task...

```

**Comment by AleksanderGrzybowski** [comment]
Make that no 'null' is printed on error, instead print stringified errors.

**Comment by AleksanderGrzybowski** [comment]
Log not just title, but also content.
